name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "aarch64-linux-android"

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3.2.1
        with:
          packages: 'platforms;android-30 build-tools;30.0.3'

      - name: Install cargo-apk
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-apk

      # --- FINAL FIX: REMOVE THE CONFLICTING FILE ---
      - name: Remove Desktop main.rs to Avoid Conflict
        run: rm src/main.rs

      #- name: Build debug APK
      #  run: cargo apk build

      - name: Build debug APK
        run: cargo apk build --lib

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: rave-engine-apk
          path: target/debug/apk/*.apk

