name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- NEW DEBUG STEP ---
      # This will print the content of the workflow file to the log.
      - name: Display Workflow File Content
        run: cat .github/workflows/build.yml

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "aarch64-linux-android"

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3.2.1
        with:
          packages: 'platforms;android-34 build-tools;34.0.0'

      - name: Install cargo-apk
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-apk

      - name: Build release APK
        run: cargo apk build --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: rave-engine-apk
          path: target/release/apk/*.apk
